### ISSUE TITLE
Nexus checklist

### ISSUE THREAD

**Issue by recursion-ninja** [amnh/PCG#17]
<a href="https://github.com/ima-hima"><img src="https://avatars0.githubusercontent.com/u/13487794?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ima-hima](https://github.com/ima-hima)**
_Thursday Mar 30, 2017 at 02:40 GMT_
_Originally opened as https://github.com/ima-hima/PCG/issues/17_

----

- [ ] Add documentations

- [ ] Data character blocks (BEGIN DATA) may be aligned.

- [ ] Check on data blocks to see if they have nchar specified, in which case they are aligned.

- [ ] Are we pulling duplicate taxon name code from nexus?

- [ ] Double check that Sankoff matrices are being pulled.

- [ ] Capture character state names.

- [ ] Double check that multiple trees are being captured.

- [ ] Check for correct number of taxa. Huh?
